### PR TITLE
Add ability to extract chunk names & numbers, and use in tempfile name

### PR DESCRIPTION
**Pull request by yogat3ch**
list_chunks:
 - captures chunk numbers and titles to use as names on list with line numbers
pretty_rmd_inline:
 - uses the chunk number and name in the suffix of the temp filename prior to "_tmp_" identifier
pretty_utils:
 - Now extracts and prints chunk number and title instead of a random tempfile name such that the user has better context for where the change is occurring in the rmd

### CODE REVIEW

**Comment by yogat3ch** [comment]
This now fixes also fixes an existing bug that would error `parse` in `pretty_parse` when only a single chunk was present in an Rmd document.

**Comment by yonicd** [comment]
can you resolve the conflict created with the merge of PR https://github.com/yonicd/sinew/pull/57 into the master branch. thanks

**Comment by yogat3ch** [comment]
Ok, I think that fixed it.

**Comment by yonicd** [comment]
looks good. that makes it much nicer thanks

**Pull request merged**
