### PR TITLE
Add View Context to package selection menu

### PR DESCRIPTION
**Pull request by yogat3ch**
Sometimes it's difficult to know which package to pick just given the options and I've thought it would be helpful to know the context in which the function is being used. 
This adds an option to the package selection menu called View Context which gives a screen print of the `txt` in questions with `{crayon}` highlighting for the function in question.
prettify.R:
 - pass `txt` to `pretty_find` to support View Context
pretty_utils.R:
 - Add while loop to allow for View Context option in package selection menu

### CODE REVIEW

**Comment by yonicd** [comment]
I thought that feature was available already. Or at least it was and the context took it's place.

**Comment by yonicd** [comment]
My memory was correct. If you set `ask = FALSE` then you get the potential changes in the console highlighted with {crayon}

**Comment by yogat3ch** [comment]
That is indeed the case when `ask = FALSE`. This allows the user to see context when prompted to select the appropriate package to aid in making the appropriate selection.

**Comment by yonicd** [comment]
got it. i'll checkout the PR to see it. I was always a bit worried that too busy of a console will confuse the user.

thanks!

**Comment by yogat3ch** [comment]
That's a valid concern. 
In the `ask = TRUE` case the code context isn't printed by default so it's just the chunk name (with the new file names for some context) and then the prompt. 
As for the prompt, I noticed that the function choices offered were often duplicating themselves 2-3 times. I'm not sure why this was happening, but `unique` now fixes that behavior. 
I tried to make the choices consistent with the current behavior: the first couple being the persistent `(*)` options, then the one time options, followed now by `View Context`, and always closing with `Ignore Instance` and `Ignore All`. 
If its a common name for a function, it can sometimes populate two rows but I haven't yet noticed it extend beyond the 1/4 view of the console yet.

**Comment by yonicd** [comment]
can you update this PR to resolve the conflict with the master

**Comment by yogat3ch** [comment]
Changed it to "Print Context" since it's actually using `print` instead of `View`. Should be fixed for merge now. I'm going to test it out a couple more times to ensure it's doing the highlighting properly.

**Comment by yogat3ch** [comment]
I'm finding something bizarre while testing this. `library` call getting repeated over and over again as the entire replacement chunk. I'm not sure if it's related to this, an earlier update, or this specific scenario. Going to debug now, just wanted to give a heads up.

**Comment by yogat3ch** [comment]
This should be good to merge now

**Comment by yonicd** [comment]
ty!

**Pull request merged**
